#!/usr/bin/env ruby

option = ARGV[0]

$rscroot = "/usr/local/etc/specto/resource"

require 'fileutils'
require 'launchy'
require '/usr/local/lib/specto/spectojuvale.rb'
#$LOAD_PATH.unshift(File.dirname("/usr/local/lib/specto/*"))

FileUtils.mkdir_p $rscroot

GUI = "g"
CUI = "cui"

KEYS_COMMAND = "see [category] ... enlist possible hyperlinks "
CAT_COMMAND = "see [lc] ... enlist categories "
PUSH_COMAND = "see add [category] [key] [url]   ... add [key][value] type bookmarks (not random)"
CALL_COMMAND = "see [category] [key] [output=\"cui/gui\"] .. obtain the url related to the key you registered"
DEL_COMMAND = "see [rmc] [category] ... delete category"

def listkeys(ci)
  file = "#{$rscroot}/#{SpectoJuvare.category(ci)}"
  puts ">> #{file}"
  arr = SpectoJuvare.file_to_array file
  puts "---keys---"
  arr.each { |line|

    linesp = line.strip.chomp.split(' ')
    puts " "+linesp[0]
  }
  puts "----------"
end

def showHelp()
  puts "========== SPECTO =========== "
  puts
  puts KEYS_COMMAND
  puts CAT_COMMAND
  puts PUSH_COMAND
  puts CALL_COMMAND
  puts DEL_COMMAND
  puts
end

def doaddop(categoryindex, pi1, pi2)
  def validate(argsize, message)
    if ARGV.size < argsize
      abort "==> "+message
    end
  end

  validate(3, PUSH_COMAND)

  key = ARGV[pi1]
  value = ARGV[pi2]
  sententia = "#{key} #{value}"

  tmp = Hash.new
  target = SpectoJuvare.getFile(SpectoJuvare.category(categoryindex))

  def concat(tmp, key, value):String
    if tmp.has_key? key
      tmp[key] + "," + value
    else
      value
    end
  end

  File.open(target, "r").each do |line|
    lsp = line.split(" ")
    tmp[lsp[0]] =  concat tmp, lsp[0], lsp[1]
  end

  tmp[key] = concat tmp, key, value

  f = File.open(SpectoJuvare.getFile(SpectoJuvare.category(categoryindex)), "w")
  tmp.keys.each do |eachkey|
    f.puts "#{eachkey} #{tmp[eachkey]}"
  end
  f.close

end

case option
  when "-h", "help", "h", ""
    showHelp
when "add"
  doaddop 1, 2, 3
when "lc" # list categories
  system "ls #{$rscroot}"
when "rmc"
  system "rm #{$rscroot}/#{SpectoJuvare.category(1)}"
when "find"
  #ARGV[0] est command
  if ARGV.size < 2
    abort "arguments required."
  end
  term = "https://www.google.co.jp/search?q="

  (1 .. ARGV.size-1).each do |i|
    if i == ARGV.size-1
      term += ARGV[i]
    else
      term += ARGV[i]+"+"
    end
  end

  Launchy.open(term)
when "todo"
  targetinf = "/usr/local/etc/specto/config"
  dirs = Array.new
  # see setting file to see the location (directory)
  # todo_dir: ....
  $todo_dir = "todo_dir:"
  File.open(targetinf, "r").each do |line|
    if line.start_with? $todo_dir
      dirs.push line
    end
  end
  # iterate files in the target directory

  def getFileContent(dir, file):Array
    arr = Array.new
    File.open("#{dir}/#{file}", "r").each do |line|
      arr.push line
    end
    arr
  end

  def isFileEligible(file):Boolean
    if ((File.directory?(file) == false) && !file.end_with?(".swp") )
      return true
    end
    return false
  end

  def get_todos(todos, contents):Array
    contents.each do |line|
      if line.include? "todo"
        todos.push "* "+line.gsub("todo","").strip
      end
    end
    return todos
  end

  def strip(line)
    begin
      return line.strip
    rescue
      return ""
    end
  end

  def rm_todos(query, contents, file, dir)
    if query == nil || query == ""
    else

      f = File.open(dir+"/"+file, "w")
      contents.each do |line|
        if ((strip(line).start_with?(query)))
          puts "deleted: #{line}"
        else
          f.puts line
        end
      end
      f.close
    end
  end

  def delete(dir, query):Array
    Dir.foreach(dir) do |file|
      if isFileEligible file
        rm_todos query, getFileContent(dir, file), file, dir
      end
    end
    return enlist(dir)
  end

  def enlist(dir):Array
    todos = Array.new
    Dir.foreach(dir) do |file|
      if isFileEligible file
        todos = get_todos(todos, getFileContent(dir, file))
      end
    end
    return todos
  end

  def collect_todos(dir, query):Array

    dir = dir.gsub($todo_dir,"").strip

    case query
    when ""
      return enlist(dir)
    else
      return delete(dir, query)
    end
  end

  query = ""
  if ARGV[1] != ""
    query = ARGV[1]
  end

  puts "--------- todos ---------"
  dirs.each do |dir|
    puts collect_todos(dir, query)
  end
  puts "-------------------------"
  # correct sentence starts from "todo"
  # show each
else
  if ARGV.size < 1
   showHelp()
  end
  if ARGV.size == 1
   listkeys(0)
   abort
  end

  key = ARGV[1]
  if key == "add"
    doaddop 0, 2, 3
    abort ""
  end

  category = SpectoJuvare.category(0)

  file = "#{$rscroot}/#{category}"

  puts file

  lines = SpectoJuvare.file_to_array file
  lines.each{ |line|
    linesp = line.strip.chomp.split(' ')
    if linesp[0] == key
      SpectoJuvare.openurl linesp[1], SpectoJuvare.get_option(ARGV[2])
    end
  }
end



