#!/usr/bin/env ruby

require 'fileutils'

src = "see"
dest = "/usr/local/bin/see"

FileUtils.copy_file(src, dest)
libdest = "/usr/local/lib/specto"
configdest = "/usr/local/etc/specto/config"
FileUtils.mkdir_p libdest
system("cp -r lib/* #{libdest}")
system("cp config #{configdest}")

src = "del"
dest = "/usr/local/bin/del"
system("cp #{src} #{dest}")
