#!/usr/bin/env ruby

require 'fileutils'

src = "specto"
dest = "/usr/local/bin/specto"

FileUtils.copy_file(src, dest)
libdest = "/usr/local/lib/specto"
configdest = "/usr/local/specto/config"
FileUtils.mkdir_p libdest
system("cp -r lib/* #{libdest}")
system("cp config #{configdest}")

