#!/usr/bin/env ruby

require 'open-uri'
require 'nokogiri'

if ARGV.size < 2
  abort "w2 [destination file] [url]"
end

url = ARGV[0] # or locale
target = ARGV[1]

def write(url, target)
  f = File.open(target,"a")
  source = Nokogiri::HTML(open(url))
  date = ""
  source.xpath("//span").each do |line|
    if line.first[1] == "date"
      date = line.content.strip.chomp
    end
    if line.first[1] == "tag-name"
      f.puts "#{line.content} (#{date})"
    end
  end
  f.close
end

if url.end_with? ".locale"
  File.open(url, "r").each do |file|
    if file.strip != ""
      write file, target
    end
  end
end

